version: '3.9'

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:23.04-py3
    ports:
      - 8000:8000 #HTTP
      - 8001:8001 #GRPC
      - 8002:8002 #Metrics
    volumes:
      - ./models:/models
    command: ["tritonserver", "--model-repository=/models"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
