version: '3.9'

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:23.04-py3
    ports:
      - 8000:8000 #HTTP
      - 8001:8001 #GRPC
      - 8002:8002 #Metrics
    volumes:
      - ./models:/models
      - ./recommendation.tar.gz:/opt/tritonserver/envs/recommendation.tar.gz
      - ./recommendation.model:/opt/tritonserver/recommendation.model
    command: ["tritonserver", "--model-repository=/models"]
    shm_size: '2g'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
